project:
  type: website
  output-dir: docs

website:
  title: "Indoor radon exposure Germany"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: model.qmd
        text: Model

  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Federal states"
        contents:
          - federal_states_AM.qmd
          - federal_states_Exc100.qmd
          - federal_states_pop.qmd
      - section: "Districts"
        contents:
          - districts_AM.qmd
          - districts_Exc100.qmd
          - districts_pop.qmd
      - section: "Municipalities"
        contents:
          - municipalities_AM.qmd
          - municipalities_Exc100.qmd
          - municipalities_pop.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



