---
project:
  type: website
  output-dir: docs
  # Ignore model.qmd, because its a dynamic and not a static page
  # https://quarto.org/docs/projects/quarto-projects.html#render-targets
  render:
    - "*.qmd"
    - "!model.qmd"

website:
  title: "Indoor radon exposure Germany"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
    # Test Model link to another container
    # https://quarto.org/docs/websites/website-navigation.html#navbar-tools
      - text: Model
        url:  https://model.radonmap.info
        

  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Federal states"
        contents:
          - federal_states_AM.qmd
          - federal_states_Exc100.qmd
          - federal_states_pop.qmd
      - section: "Districts"
        contents:
          - districts_AM.qmd
          - districts_Exc100.qmd
          - districts_pop.qmd
      - section: "Municipalities"
        contents:
          - municipalities_AM.qmd
          - municipalities_Exc100.qmd
          - municipalities_pop.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
execute: 
  cache: true



