project:
  type: website
  output-dir: docs

website:
  title: "Indoor radon exposure Germany"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - federal_states.qmd
      - districts.qmd
      # - municipalities.qmd
      # - model.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



